library(MASS)
library(tidyverse)
library(mlbench)
library(caret)
library(survey)
library(sampling)
library(NonProbEst)
library(xgboost)
library(dplyr)
library(foreign)
library(RcmdrMisc)
library(samplingVarEst)
# install.packages("devtools")
# library(devtools)
library(fastDummies)
library(parallel)
library(lme4)
#library(FSelector)
#remotes::install_github("ncn-foreigners/nonprobsvy")
library(nonprobsvy)
library(Frames2)
#library(xlsx)
# if (!require("devtools")) install.packages("devtools")
# devtools::install_github("chkern/KWML")
library(KWML)
#install.packages("nnet")
library(nnet)
library(xlsx)

for(n_r in c(500, 1000, 1500, 2000, 2500)){
  source("simulation nr.R")  
  setwd("...")
  write.xlsx(results, paste0("results_",n_r,".xlsx"))
}