library(MASS)
library(tidyverse)
library(mlbench)
library(caret)
library(survey)
library(sampling)
library(NonProbEst)
library(xgboost)
library(dplyr)
library(foreign)
library(RcmdrMisc)
library(samplingVarEst)
# install.packages("devtools")
# library(devtools)
library(fastDummies)
library(parallel)
library(lme4)
#library(FSelector)
#remotes::install_github("ncn-foreigners/nonprobsvy")
library(nonprobsvy)
library(Frames2)
#library(xlsx)
# if (!require("devtools")) install.packages("devtools")
# devtools::install_github("chkern/KWML")
library(KWML)
#install.packages("nnet")
library(nnet)
library(xlsx)

cluster = makeCluster(3) #para que no coja todos los nucleos? OJO QUE LOS COJO TODOS PARA QUE TARDE MENOS
clusterEvalQ(cluster,library(MASS))
clusterEvalQ(cluster,library(tidyverse))
clusterEvalQ(cluster,library(mlbench))
clusterEvalQ(cluster,library(xgboost))
clusterEvalQ(cluster,library(foreign))
clusterEvalQ(cluster,library(RcmdrMisc))
clusterEvalQ(cluster,library(fastDummies))
clusterEvalQ(cluster,library(lme4))
clusterEvalQ(cluster,library(NonProbEst))
clusterEvalQ(cluster,library(caret))
clusterEvalQ(cluster,library(sampling))
clusterEvalQ(cluster,library(survey))
#clusterEvalQ(cluster,library(FSelector))
clusterEvalQ(cluster,library(KWML))
clusterEvalQ(cluster,library(samplingVarEst))
#remotes::install_github("ncn-foreigners/nonprobsvy")
clusterEvalQ(cluster,library(nonprobsvy))
clusterEvalQ(cluster,library(dplyr))
clusterEvalQ(cluster,library(Frames2))
#clusterEvalQ(cluster,library(xlsx))
clusterEvalQ(cluster,library(KWML))
clusterEvalQ(cluster,library(nnet))

n_redes1=c("Highly Connected Groups", "Scale free", "Small Groups")
n_r=1000 #Como en el que calculamos las varianzas

for(escenario in n_redes1){
  source("simulation1.R")  
  setwd("C:/Users/jorge/Desktop/EST/TI/2024-2025 (2º Año Doctorado)/Artículos/Artículo Ismael/Escenario Inicial (estudio simul art)/Nuevas redes")
  write.xlsx(results, paste0("results",escenario,".xlsx"))
}


n_redes2=c("sim2a 3 seeds", "sim2b 8 seeds")

for(escenario in n_redes2){
  source("simulation2.R")  
  setwd("C:/Users/jorge/Desktop/EST/TI/2024-2025 (2º Año Doctorado)/Artículos/Artículo Ismael/Escenario Inicial (estudio simul art)/Nuevas redes")
  write.xlsx(results, paste0("results",escenario,".xlsx"))
}
